GOOGLE_CLIENT_ID=your_client_id_from_google_cloud_console
GOOGLE_CLIENT_SECRET=your_client_secret_from_google_cloud_console
GOOGLE_CALLBACK_URL=http://localhost:3000/auth/google/callback
MONGODB_URI=your_mongodb_connection_string
SESSION_SECRET=any_random_string_for_session 